spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/user/**
        - id: QuizService
          uri: lb://QuizService
          predicates:
            - Path=/quiz/**

server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka